version: '3.9'
services:
  client:
    extends: 
      file: client/docker-compose.yml
      service: client
    networks:
      - internal
    depends_on: 
      - server

  server:
    extends: 
      file: server/docker-compose.yml
      service: server
    networks:
      - internal


networks:
  internal:
    name: enigma
