name: Go Server Build

on:
  push:
    branches:
      - main
    paths:
      - server/go/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/pradyumnakrishna/enigma-protocol

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set DATE
        run: echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Go Server
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: server/go
          push: true
          tags: ${{ env.IMAGE_NAME }}/go-server:latest,${{ env.IMAGE_NAME }}/go-server:${{ env.DATE }}
